//
//  PhoneDetailsInteractor.swift
//  ShopPhone
//
//  Created by GABLET04690 on 20/12/2562 BE.
//  Copyright (c) 2562 Orathai Udomluk. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol PhoneDetailsBusinessLogic {
    func getPhoneDetailImageList()
    func getPhoneDetailImage(imageURL: String)
    func getPhoneDetail(phoneName: inout String, description: inout String, phonePrice: inout Double, phoneRating: inout Double)
}

protocol PhoneDetailsDataStore {
  var phoneId: Int { get set }
  var name: String { get set }
  var phoneDescription: String { get set }
  var price: Double { get set }
  var rating: Double { get set }
}

class PhoneDetailsInteractor: PhoneDetailsBusinessLogic, PhoneDetailsDataStore {
  var presenter: PhoneDetailsPresentationLogic?
  var phoneDetailsWorker: PhoneDetailsWorker?
  var phoneId: Int = 0
  var name: String = ""
  var phoneDescription: String = ""
  var price: Double = 0.0
  var rating: Double = 0.0
  var realmManager: RealmManagerProtocol?
  
  private func prepare() {
      if realmManager == nil {
          realmManager = RealmManager()
      }
      
      if phoneDetailsWorker == nil {
          phoneDetailsWorker = PhoneDetailsWorker()
      }
   }
    
    func getPhoneDetailImageList() {
        prepare()
        
        phoneDetailsWorker?.getPhoneImageList(Id: phoneId, completion: {
            (result) in switch result {
            case .Success(let data):
                let response = PhoneDetails.PhoneImageList.Response(result: data)
                self.presenter?.presentPhoneImageListData(response: response)
            case .Error(let error):
                print("Error Can't Get Path Phone Image : \(error.localizedDescription)")
                self.presenter?.presentAlertCannotGetPhoneImage()
            }
        })
    }
    
    func getPhoneDetailImage(imageURL: String) {
        prepare()
        
        phoneDetailsWorker?.getPhoneDetailsImage(url: imageURL, completion: {
            (result) in switch result {
            case .Success(let image):
                let response = PhoneDetails.PhoneImage.Response(phoneImage: image)
                self.presenter?.presentPhoneImage(response: response)
            case .Error(let error):
                print("Error Get Phone Image: \(error.localizedDescription)")
                self.presenter?.presentAlertCannotGetPhoneImage()
            }
        })
    }
    
    func getPhoneDetail(phoneName: inout String, description: inout String, phonePrice: inout Double, phoneRating: inout Double) {
        phoneName = name
        description = phoneDescription
        phonePrice = price
        phoneRating = rating
    }
}
