//
//  PhoneDetailsModels.swift
//  ShopPhone
//
//  Created by GABLET04690 on 20/12/2562 BE.
//  Copyright (c) 2562 Orathai Udomluk. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PhoneDetails {
  enum PhoneImageList {
    struct Request {
      var phoneId: Int
    }
    struct Response {
      var result: PhoneImageModel?
    }
    struct ViewModel {
      var result: PhoneImageModel?
    }
  }
    
    enum PhoneImage {
        struct Request {
          var url: String
        }
        struct Response {
          var phoneImage: UIImage
        }
        struct ViewModel {
          var phoneImage: UIImage
        }
    }
}
