//
//  PhoneDetailsPresenter.swift
//  ShopPhone
//
//  Created by GABLET04690 on 20/12/2562 BE.
//  Copyright (c) 2562 Orathai Udomluk. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhoneDetailsPresentationLogic {
    func presentPhoneImageListData(response: PhoneDetails.PhoneImageList.Response)
    func presentPhoneImage(response: PhoneDetails.PhoneImage.Response)
    func presentAlertCannotGetPhoneImage()
}

class PhoneDetailsPresenter: PhoneDetailsPresentationLogic {
  weak var viewController: PhoneDetailsDisplayLogic?
  
    func presentPhoneImageListData(response: PhoneDetails.PhoneImageList.Response) {
        if response.result != nil {
            let viewModel = PhoneDetails.PhoneImageList.ViewModel(result: response.result)
            viewController?.getPhoneImageListDataSuccess(viewModel: viewModel)
        } else {
            viewController?.getPhoneImageListDataFailed()
        }
    }
    
    func presentPhoneImage(response: PhoneDetails.PhoneImage.Response) {
        let viewModel = PhoneDetails.PhoneImage.ViewModel(phoneImage: response.phoneImage)
        viewController?.getPhoneImageSuccess(viewModel: viewModel)
    }
    
    func presentAlertCannotGetPhoneImage() {
        viewController?.showAlertCannotGetPhoneImage()
    }
}
