//
//  PhoneListModels.swift
//  ShopPhone
//
//  Created by GABLET04690 on 20/12/2562 BE.
//  Copyright (c) 2562 Orathai Udomluk. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PhoneList {
    enum PhoneData {
        struct Response {
            var result: PhoneDataModel
        }
        struct ViewModel {
            var result: PhoneDataModel
        }
    }
    
    enum PhoneDetails {
        struct Request {
            var phoneId: Int
            var name: String
            var phoneDescription: String
            var price: Double
            var rating: Double
        }
    }
    
    enum PhoneFavourite {
        struct Request {
            var favouritePhone: PhoneDataModel?
        }
        struct Response {
            var result: [Int]
        }
        struct ViewModel {
            var result: [Int]
        }
    }
}
