//
//  PhoneListRouter.swift
//  ShopPhone
//
//  Created by GABLET04690 on 20/12/2562 BE.
//  Copyright (c) 2562 Orathai Udomluk. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

import UIKit

@objc protocol PhoneListRoutingLogic {
  func routeToPhoneDetails(segue: UIStoryboardSegue?)
}

protocol PhoneListDataPassing {
  var dataStore: PhoneListDataStore? { get }
}

class PhoneListRouter: NSObject, PhoneListRoutingLogic, PhoneListDataPassing {
  weak var viewController: PhoneListViewController?
  var dataStore: PhoneListDataStore?
  
  // MARK: Routing
    func routeToPhoneDetails(segue: UIStoryboardSegue?) {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "PhoneDetailsViewController") as! PhoneDetailsViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToPhoneDetails(source: dataStore!, destination: &destinationDS)
        navigateToPhoneDetails(source: viewController!, destination: destinationVC)
    }

  // MARK: Navigation
  func passDataToPhoneDetails(source: PhoneListDataStore, destination: inout PhoneDetailsDataStore) {
      destination.phoneId = source.phoneId
    destination.name = source.name
    destination.phoneDescription = source.phoneDescription
    destination.price = source.price
    destination.rating = source.rating
  }
  
  // MARK: Passing data
  func navigateToPhoneDetails(source: PhoneListViewController, destination: PhoneDetailsViewController) {
      source.show(destination, sender: nil)
   }
}
