//
//  PhoneListWorker.swift
//  ShopPhone
//
//  Created by GABLET04690 on 20/12/2562 BE.
//  Copyright (c) 2562 Orathai Udomluk. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Moya
import SwiftyJSON

class PhoneListWorker {
    let phoneDataServiceProvider = MoyaProvider<PhoneDataService>()
    
    func getPhoneListData(completion: @escaping (Result<PhoneDataModel>) -> Void) {
        phoneDataServiceProvider.request(.getPhoneListData, completion: { (result) in
            switch result {
            case .success(let response):
                do {
                    let responseFilter = try response.filterSuccessfulStatusCodes()
                    let jsonArray = try JSON(data: responseFilter.data)
                    var jsonData: JSON
                    for item in jsonArray {
                        jsonData = item.1
                        completion(.Success(try PhoneDataModel(json: jsonData)))
                    }
                } catch let error {
                    completion(.Error(error))
                    print("Error Map Phone Data : \(error)")
                }
            case .failure(let error) :
                return completion(.Error(error))
            }
        })
    }
}
