//
//  PhoneListInteractor.swift
//  ShopPhone
//
//  Created by GABLET04690 on 20/12/2562 BE.
//  Copyright (c) 2562 Orathai Udomluk. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhoneListBusinessLogic
{
  func doSomething(request: PhoneList.Something.Request)
}

protocol PhoneListDataStore
{
  //var name: String { get set }
}

class PhoneListInteractor: PhoneListBusinessLogic, PhoneListDataStore
{
  var presenter: PhoneListPresentationLogic?
  var worker: PhoneListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PhoneList.Something.Request)
  {
    worker = PhoneListWorker()
    worker?.doSomeWork()
    
    let response = PhoneList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
