//
//  PhoneListPresenter.swift
//  ShopPhone
//
//  Created by GABLET04690 on 20/12/2562 BE.
//  Copyright (c) 2562 Orathai Udomluk. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhoneListPresentationLogic {
    func presentAllPhoneListData(response: PhoneList.PhoneData.Response)
    func presentPhoneDetails()
    func presentUpdateFavouritePhoneCell()
    func presentFavouritePhoneData(response: PhoneList.PhoneFavourite.Response)
    func presentAlertConnectionFail()
}

class PhoneListPresenter: PhoneListPresentationLogic {
  weak var viewController: PhoneListDisplayLogic?
    
    func presentAllPhoneListData(response: PhoneList.PhoneData.Response) {
        let viewModel = PhoneList.PhoneData.ViewModel(result: response.result)
        viewController?.getAllPhoneListDataSuccess(viewModel: viewModel)
    }
  
    func presentPhoneDetails() {
        viewController?.navigateToPhoneDetails()
    }
    
    func presentUpdateFavouritePhoneCell() {
        viewController?.updateFavouritePhoneCell()
    }
    
    func presentFavouritePhoneData(response: PhoneList.PhoneFavourite.Response) {
        let viewModel = PhoneList.PhoneFavourite.ViewModel(result: response.result)
        viewController?.getFavouritePhoneData(viewModel: viewModel)
    }
    
    func presentAlertConnectionFail() {
        viewController?.showAlertConnectionFail()
    }
}
